kind: pipeline
type: docker
name: build-and-deploy

steps:
- name: install
  image: node:16
  commands:
    - npm install

- name: build
  image: node:16
  commands:
    - npx tailwindcss -i ./src/input.css -o ./dist/output.css --minify

- name: docker-build
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: mahendra968/drone-demo  # sesuaikan dengan nama repo Anda
    tags:
      - latest
      - ${DRONE_COMMIT_SHA:0:8}
    dockerfile: Dockerfile

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: SSH_HOST
    username:
      from_secret: SSH_USERNAME
    password:
      from_secret: ssh_key
    port: 22
    script:
      - docker pull mahendra968/drone-demo:latest
      - docker stop drone-demo || true
      - docker rm drone-demo || true
      - docker run -d --name drone-demo -p 80:80 mahendra968/drone-demo:latest

trigger:
  branch:
    - main
    - master
  event:
    - push

volumes:
- name: cache
  host:
    path: /tmp/cache

---
# Pipeline untuk Pull Request
kind: pipeline
type: docker
name: pull-request

steps:
- name: install
  image: node:16
  commands:
    - npm install

- name: build
  image: node:16
  commands:
    - npx tailwindcss -i ./src/input.css -o ./dist/output.css --minify

trigger:
  event:
    - pull_request
