# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json for npm install
COPY package*.json ./

# Install the app dependencies
RUN npm install

# Copy the entire application into the container
COPY . .

# Ensure that dist folder is included in the container
RUN mkdir -p /app/dist

# If the dist folder is generated by a build tool (like Vite or Webpack), ensure you run the build step
RUN npm run build  # This command depends on how your build is set up (e.g., `npm run build` for Vite)

# Expose the port the app runs on
EXPOSE 3000

# Command to run the app
CMD ["npm", "start"]
